#!/usr/bin/env python3

import json
import sqlite3
import urllib.request

def main():
    conn = sqlite3.connect('seng/db.sqlite3')
    curs = conn.cursor()

    curs.execute('DELETE FROM server_company')

    for ric, name in COMPANIES:
        curs.execute('INSERT INTO server_company (ric, name) VALUES (?, ?)', (ric, name))

    conn.commit()

COMPANIES = [
    ('005490', 'POSCO'),
    ('1088', 'China Shenhua Energy Company Limited'),
    ('2002', 'China Steel Corporation'),
    ('2899', 'Zijin Mining Group Company Limited'),
    ('3668', 'CHINALCO-CMC'),
    ('4188', 'Mitsubishi Chemical Holdings Corp'),
    ('4612', 'Nippon Paint Holdings Co Ltd'),
    ('5411', 'JFE Holdings, Inc.'),
    ('600019', 'Baosteel'),
    ('600188', 'Yanzhou Coal'),
    ('600362', 'Jiangxi Copper Co Ltd'),
    ('601088', 'China Shenhua'),
    ('601898', 'China Coal Energy Co Ltd'),
    ('601899', 'Zijin Mining'),
    ('8002', 'Marubeni Corp'),
    ('8053', 'Sumitomo Corp'),
    ('8058', 'Mitsubishi Corp'),
    ('9179', 'Kawasaki Kinkai Kisen Kaisha Ltd'),
    ('AA', 'Alcoa Corp'),
    ('AAL', 'Anglo American plc'),
    ('ABBV', 'AbbVie Inc.'),
    ('ABI', 'Anheuser-Busch InBev SA/NV'),
    ('ABX', 'Barrick Gold Corporation'),
    ('ADRO', 'Adaro Energy Tbk.'),
    ('AGO', 'Atlas Iron Limited'),
    ('AGRO3', 'BrasilAgro - Companhia Brasileira de Propriedades Agrícolas'),
    ('ANRZQ', 'Alpha Natural Resources, Inc.'),
    ('ANTO', 'Antofagasta plc'),
    ('ANZ', 'Australia and New Zealand Banking Group Limited'),
    ('APF', 'Anglo Pacific Group plc'),
    ('ARI', 'Arrium Ltd'),
    ('ARWR', 'Arrowhead Pharmaceuticals Inc'),
    ('ASR', 'Alacer Gold Corp.'),
    ('ATLN', 'Actelion Ltd'),
    ('AZN', 'AstraZeneca PLC'),
    ('BABA', 'Alibaba Group Holding Ltd'),
    ('BAC', 'Bank of America Corp'),
    ('BARC', 'Barclays PLC'),
    ('BAS', 'Basic Energy Services Inc'),
    ('BBCN', 'Bancorp Inc'),
    ('BCI', 'BC Iron Limited'),
    ('BDR', 'Beadell Resources Limited'),
    ('BG', 'BG Group'),
    ('BHP', 'BHP Billiton Limited'),
    ('BLDR', 'Builders FirstSource Inc'),
    ('BLK', 'BlackRock, Inc.'),
    ('BLT', 'BHP Billiton plc'),
    ('BP', 'BP p.l.c.'),
    ('BTU', 'Peabody Energy Corp'),
    ('CBA', 'Commonwealth Bank of Australia'),
    ('CENX', 'Century Aluminum Co'),
    ('CGIX', 'Cancer Genetics Inc'),
    ('CIG', 'Companhia Energetica de Minas Gerais CEMIG'),
    ('CLF', 'Cliffs Natural Resources Inc'),
    ('CMG', 'Chipotle Mexican Grill Inc'),
    ('CMP', 'Compass Minerals International, Inc.'),
    ('CVX', 'Chevron Corporation'),
    ('DATA', 'Tableau Software Inc'),
    ('DD', 'E I du Pont de Nemours and Co'),
    ('DIS', 'Walt Disney Co'),
    ('DOW', 'Dow Chemical Co'),
    ('DVN', 'Devon Energy Corp'),
    ('DWA', 'DreamWorks Animation LLC'),
    ('EPD', 'Enterprise Products Partners LP'),
    ('EVN', 'Evolution Mining Limited'),
    ('EYES', 'Second Sight Medical Products Inc'),
    ('FCX', 'Freeport-McMoRan Inc'),
    ('FIBR3', 'Fibria Celulose S.A.'),
    ('FLR', 'Fluor Corp'),
    ('FMG', 'Fortescue Metals Group Limited'),
    ('FNV', 'Franco-Nevada Corporation'),
    ('GLEN', 'Glencore Plc'),
    ('GLUU', 'Glu Mobile Inc'),
    ('GMCR', 'Keurig Green Mountain Inc'),
    ('GS', 'Goldman Sachs Group Inc'),
    ('GSK', 'GlaxoSmithKline plc'),
    ('HBM', 'Hudbay Minerals Inc.'),
    ('HL', 'Hecla Mining Co'),
    ('HMSO', 'Hammerson plc'),
    ('HOT', 'Starwood Hotels & Resorts Worldwide Inc.'),
    ('HSBA', 'HSBC Holdings plc'),
    ('HZNP', 'Horizon Pharma PLC'),
    ('ICON', 'Iconix Brand Group Inc'),
    ('IGO', 'Independence Group NL'),
    ('IHG', 'InterContinental Hotels Group PLC'),
    ('JNJ', 'Johnson & Johnson'),
    ('JPM', 'JPMorgan Chase & Co'),
    ('KBIO', 'KaloBios Pharmaceuticals Inc'),
    ('KHC', 'Kraft Heinz Co'),
    ('KKR', 'KKR & Co LP'),
    ('KMD', 'Kathmandu Holdings Limited'),
    ('KMI', 'Kinder Morgan Inc'),
    ('LND', 'Brasilagro Companhia Brasileira de Propriedades Agricolas'),
    ('LXRX', 'Lexicon Pharmaceuticals Inc'),
    ('MNST', 'Monster Beverage Corp'),
    ('MQG', 'Macquarie Group Limited'),
    ('MRNS', 'Marinus Pharmaceuticals Inc'),
    ('MRVL', 'Marvell Technology Group Ltd'),
    ('MS', 'Morgan Stanley'),
    ('MW', "Men's Wearhouse Inc"),
    ('MYR', 'Myer Holdings Limited'),
    ('NAB', 'National Australia Bank Limited'),
    ('NCM', 'Newcrest Mining Limited'),
    ('NOBG', 'Noble'),
    ('NOVN', 'Novartis AG'),
    ('NPT', 'NetPlay TV plc'),
    ('NUF', 'Nufarm Limited'),
    ('NVDA', 'NVIDIA Corp'),
    ('OGC', 'OceanaGold Corporation'),
    ('OIBR', 'Oi SA'),
    ('OIBR3', 'Oi S.A.'),
    ('OR', 'Osisko Gold Royalties Ltd.'),
    ('ORG', 'Origin Energy Limited'),
    ('OSH', 'Oil Search Limited'),
    ('OZL', 'OZ Minerals Limited'),
    ('PAOC', 'Pan Ocean Container Supplies Ltd.'),
    ('PATAQ', 'Patriot Coal Corp'),
    ('PBY', 'Pep Boys'),
    ('PICK', 'iShares MSCI Global Metals & Mining Producers ETF'),
    ('QRVO', 'Qorvo Inc'),
    ('RBS', 'The Royal Bank of Scotland Group plc'),
    ('RDSA', 'Royal Dutch Shell plc'),
    ('REDY', "Dr.Reddy's Laboratories Ltd"),
    ('RF', 'Regions Financial Corp'),
    ('RGLD', 'Royal Gold Inc'),
    ('RIO', 'Rio Tinto Limited'),
    ('ROD', 'Sportech PLC'),
    ('RR', 'Rolls-Royce Holdings plc'),
    ('RRL', 'Regis Resources Limited'),
    ('RS', 'Reliance Steel & Aluminum Co'),
    ('S32', 'South32 Limited'),
    ('SAMNE', 'Samarco Mineracao SA'),
    ('SASY', 'Sanofi SA'),
    ('SEA', 'Seabridge Gold Inc.'),
    ('SFR', 'Sandfire Resources NL'),
    ('SHAK', 'Shake Shack Inc'),
    ('SIP', 'Sigma Pharmaceuticals Limited'),
    ('SLW', 'Silver Wheaton Corp.'),
    ('SMR', 'Stanmore Coal Limited'),
    ('SONA', 'Sona Petroleum Bhd'),
    ('STI', 'SunTrust Banks Inc'),
    ('STLD', 'Steel Dynamics Inc'),
    ('STMP', 'Stamps.Com Inc'),
    ('STO', 'Santos Limited'),
    ('SUZB5', 'Suzano Papel e Celulose S.A.'),
    ('SYNN', 'Syngenta AG'),
    ('TCKB', 'Teck Resources Ltd'),
    ('TIGERBRD', 'Tiger Branded Consumer Goods PLC'),
    ('TISC', 'Tata Steel Ltd'),
    ('TNGO', 'Tangoe Inc'),
    ('TRGP', 'Targa Resources Corp'),
    ('TRIP', 'TripAdvisor Inc'),
    ('TRUE', 'TrueCar Inc'),
    ('TTWO', 'Take Two Interactive Software Inc'),
    ('VALE', 'Valecha Engineering Ltd'),
    ('VALE5', 'Vale S.A.'),
    ('VRX', 'Valeant Pharmaceuticals International, Inc.'),
    ('WBC', 'Westpac Banking Corporation'),
    ('WHC', 'Whitehaven Coal Limited'),
    ('WIBC', 'Wilshire Bancorp Inc'),
    ('WLTGQ', 'New Wei Inc'),
    ('WOR', 'WorleyParsons Limited'),
    ('WPL', 'Woodside Petroleum Ltd'),
    ('WTW', 'Weight Watchers International Inc'),
    ('X', 'United States Steel Corp'),
    ('XME', 'SPDR S&P Metals & Mining ETF'),
    ('XOM', 'Exxon Mobil Corp'),
    ('XTAXS', 'Glencore Canada Corporation'),
    ('YAL', 'Yancoal Australia Ltd'),
    ('YHOO', 'Yahoo! Inc'),
    ('YOKU', 'Youk Tudo Inc'),
    ('ZSPH', 'ZS Pharma Inc'),
]

if __name__ == '__main__':
    main()
