# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=120)),
                ('time_stamp', models.DateTimeField()),
                ('headline', models.CharField(max_length=30)),
                ('news_text', models.TextField()),
                ('instrument_ids', models.TextField()),
                ('topic_codes', models.TextField()),
                ('query_instrument_ids', models.TextField()),
                ('query_topic_codes', models.TextField()),
            ],
        ),
    ]
