# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ric', models.CharField(max_length=20)),
                ('relative_date', models.IntegerField()),
                ('date', models.DateField()),
                ('adjusted_close', models.FloatField()),
                ('return_value', models.FloatField()),
                ('pc_return', models.FloatField()),
                ('cm_return', models.FloatField()),
                ('av_return', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set([('ric', 'date')]),
        ),
    ]
