# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtrend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='close',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='open',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='volume',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
