# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtrend', '0002_auto_20170522_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ric', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('schema', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companyrating',
            unique_together=set([('ric', 'date', 'schema')]),
        ),
    ]
