# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='language',
            field=models.CharField(default='en', max_length=5),
            preserve_default=False,
        ),
    ]
