# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_newsarticle_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleRIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ric', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticleTopicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='instrument_ids',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='query_instrument_ids',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='query_topic_codes',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='topic_codes',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='uri',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='newsarticletopiccode',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.NewsArticle'),
        ),
        migrations.AddField(
            model_name='newsarticleric',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.NewsArticle'),
        ),
        migrations.AlterUniqueTogether(
            name='newsarticletopiccode',
            unique_together=set([('article', 'topic_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='newsarticleric',
            unique_together=set([('article', 'ric')]),
        ),
    ]
