# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170405_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='polarity',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subjectivity',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
    ]
