# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170505_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ric', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
