# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_stockexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
